[package]
name = "leben-regex"
version = "0.1.0"
edition = "2024"

[dependencies]
parsable = { git = "https://github.com/LeonardBengtsson/parsing-library.git" }
serde = "1.0.228"
thiserror = "2.0.18"
